Project_Management/Project_Management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='Home'),
    url(r'^home/', IndexView.as_view(), name='Home'),
    url(r'^user/', include('user.urls', namespace='user')),
]

Project_Management/user/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'user/Login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/user/login'}, name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    # url(r'^profile/', )
]

Project_Management/project/models.py
from django.db import models
from user.models import UserInfo


class ProjectInfo(models.Model):
    team_leader = models.CharField(UserInfo, max_length=50)

Project_Management/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    username = models.CharField(max_length = 50)
    Position_Choice = (
        ('Team Leader', 'Team Leader'),
        ('Developer', 'Developer'),
    )
    position = models.CharField(max_length=30, choices=Position_Choice)

    def __str__(self):
        return str(self.username)

Project_Management/user/forms.py
from django import forms
from .models import UserInfo


class LoginForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['username', 'password']
        widgets = {'password': forms.PasswordInput()}


class RegisterForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'position']
        widgets = {'password': forms.PasswordInput()}

Project_Management/Project_Management/views.py
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = 'home/index.html'


Project_Management/project/views.py
from django.shortcuts import render

# Create your views here.

Project_Management/user/views.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import *


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'user/register.html'

    def get(self, request,):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email_id = form.cleaned_data['email']
            position = form.cleaned_data['position']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, template_name='home/index.html')  # return redirect('home:Home')
        return render(request, self.template_name, {'form': form})

'''
class ProfileView(View):
    template_name = '''

Project_Management/templates/home/base.html
<body>
{% block body %}
</body>
{% endblock %}
</html>

Project_Management/templates/home/index.html
<html>
<head>
    <title> {% block title %}Project Hub{% endblock %}</title>
{% load staticfiles %}
    <link type="text/css"  href="{% static 'home/css/style.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'home/js/jquery-1.3.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/cufon-yui.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/arial.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/cuf_run.js' %}"></script>
</head>

<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="index.html"><span>Project </span>Hub</a></h1>
      </div>
	  {% block nav-global %}
      <div class="menu_nav">
        <ul>
			{% if request.user.is_authenticated %}
				<li><a href="{% url 'user:logout' %}"> Logout</a></li>
			{% else %}
				<li><a href="{% url 'user:login' %}"> Log in</a></li>
				<li><a href="{% url 'user:register' %}"> Sign Up</a></li>
			{% endif %}
        </ul>
      </div>
	  {% endblock %}
</div>
 </div>
</div>

      <div class="clr"></div>
      <div class="hbg"><img src="{% static 'home/images/header_images.jpg' %}" width="430" height="315" alt="" class="fl" />
        <div class="info fl">
          <h3>BUILD BETTER SOFTWARE <br />
            TOGETHER</h3>
        </div>
        <div class="clr"></div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
        
      </div>
      <div class="sidebar">
        <div class="gadget">
          <div class="search">
            <form method="get" id="search" action="#">
              <span>
              <input type="text" value="Search..." name="s" id="s" />
              <input name="searchsubmit" type="image" src="{% static 'home/images/search.gif' %}" value="Go" id="searchsubmit" class="btn"  />
              </span>
            </form>
            <div class="clr"></div>
          </div>
        </div>
        <div class="gadget">
          <h2 class="star"><span>Menu</span></h2>
          <div class="clr"></div>
          <ul class="sb_menu">
            <li class="active">
			<a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">&copy; Copyright <a href="#">Project Hub</a>.</p>
      <div class="clr"></div>
    </div>
  </div>
</body>
</html>

Project_Management/user/templates/user/Login.html
<html>
<head>
{% block head %}
    <title> {% block title %}Project Hub| Login{% endblock %}</title>
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.min.css' %}">
{% endblock %}
</head>
{% block body %}
<body>
    <div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="/"><span>Project </span>Hub</a></h1>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
    <div class="row">
    <div class="col-sm-12 col-md-7">
    <div class="panel panel-default">
    <div class="panel-body">
        <h3> Login </h3>
    {% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
    {% endif %}
        <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    <span> {{ field.errors }}</span>
                </div>
                <label> {{ field.label_tag }}</label>{{ field }}
            {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success" name="Submit"> Login </button>
                </div>
            </div>
        </form>
    </div>
</div>
    </div>
   </div>
</div>
{% endblock %}
</body>
</html>

Project_Management/user/templates/user/profile.html
<html>
<head>
{% block head %}
    <title> {% block title %}Project Hub| Login{% endblock %}</title>
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.min.css' %}">
{% endblock %}
</head>
{% block body %}
<body>
    <div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="/"><span>Project </span>Hub</a></h1>
      </div>
    </div>
  </div>
</div>

{% endblock %}
</body>
</html>

Project_Management/user/templates/user/register.html

<html>
<head>
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/bootstrap-theme.min.css' %}">

<title>
    Project Hub | User Register
</title>
</head>
<body>
    <div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="/"><span>Project </span>Hub</a></h1>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                <h3> Create A New Account </h3>
            {% if error_message %}
            <p><strong> {{ error_message }}</strong></p>
            {% endif %}
                <form action="" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for field in form %}
                        <div>
                            <span> {{ field.errors }}</span>
                        </div>
                        <label> {{ field.label_tag }}</label>{{ field }}
                    {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success" name="Submit"> Register </button>
                        </div>
                </div>
                </form>
                    </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>